import Link from "next/link";
import {ArrowRight,BarChart3,BrainCircuit,Check,ShieldCheck} from "lucide-react";

export default function Home(){return <main>
 <section className="mx-auto grid min-h-[76vh] max-w-7xl items-center gap-14 px-6 py-20 lg:grid-cols-[1.08fr_.92fr]">
  <div><p className="eyebrow">INTELLIGENT CREDIT RISK</p><h1 className="mt-5 max-w-3xl text-5xl font-bold leading-[1.08] tracking-[-.04em] md:text-7xl">Clarity for every lending decision.</h1><p className="muted mt-6 max-w-xl text-lg leading-8">Fast, explainable loan-default assessment with the portfolio intelligence your team needs—without the noise.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="button flex items-center gap-2" href="/predict">Assess an application <ArrowRight size={18}/></Link><Link className="rounded-xl border border-white/15 px-5 py-3 font-semibold hover:border-cyan/40" href="/dashboard">View dashboard</Link></div><div className="mt-9 flex flex-wrap gap-5 text-sm text-slate-500"><span className="flex items-center gap-2"><Check size={15} className="text-cyan"/>95% model gate</span><span className="flex items-center gap-2"><Check size={15} className="text-cyan"/>Explainable results</span></div></div>
  <div className="panel relative overflow-hidden p-6 md:p-8"><div className="absolute right-0 top-0 h-40 w-40 rounded-full bg-cyan/10 blur-3xl"/><div className="flex items-center justify-between"><div><p className="text-xs tracking-widest text-slate-500">LIVE ASSESSMENT</p><p className="mt-2 font-semibold">Application #LG-2841</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-400">Low risk</span></div><div className="my-10"><span className="text-6xl font-bold">12.4</span><span className="text-2xl text-slate-500">%</span><p className="mt-2 text-sm text-slate-500">Predicted probability of default</p></div><div className="h-2 rounded-full bg-white/[.07]"><div className="h-full w-[12.4%] rounded-full bg-cyan"/></div><div className="mt-8 grid grid-cols-3 gap-3"><Tile l="Risk score" v="124"/><Tile l="Confidence" v="87.6%"/><Tile l="Decision" v="Approve"/></div><div className="mt-4 rounded-xl border border-white/[.07] bg-white/[.025] p-4 text-sm text-slate-400">Stable income and a healthy loan-to-income ratio reduce expected risk.</div></div>
 </section>
 <section className="mx-auto grid max-w-7xl gap-4 px-6 pb-12 md:grid-cols-3"><Feature icon={<BrainCircuit/>} title="Explainable AI" text="Understand the signals behind every score."/><Feature icon={<BarChart3/>} title="Portfolio analytics" text="Monitor risk, approvals and trends in real time."/><Feature icon={<ShieldCheck/>} title="Secure workflow" text="Role-based access and auditable prediction history."/></section>
 </main>}
function Tile({l,v}:{l:string,v:string}){return <div className="rounded-xl border border-white/[.07] p-3"><p className="text-[10px] uppercase tracking-wider text-slate-500">{l}</p><p className="mt-1 font-semibold">{v}</p></div>}
function Feature({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="panel p-6"><span className="text-cyan">{icon}</span><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="muted mt-2 text-sm leading-6">{text}</p></div>}
